### ISSUE TITLE
Collision detection on the big cube.

### ISSUE THREAD

**Issue by bobtat** [RobertTatoian/FaceMapping#7]
Each cube should keep themselves inside the big cube.

**Comment by bobtat** [comment]
@WarrenGM What do you think about collison detection with the other cubes as well? Do you think that's something we should & have the time to implement?

**Comment by warrengm** [comment]
@RobertTatoian Yes, thats something we can do. The cube class has a Cube.intersects(Cube) method which can be used to detect collisions. However, I just realized that it won't detect a collision 100% percent of the time (it's possible for it to return false even though they actually collide). Alternatively, we could use absolute bounding boxes but then we have the problem of false positives instead of false negatives. The main problem right now is that it won't detect when two edges collide.

I looked into the Separating Axis Theorem which should work 100% of the time but it's less efficient and fairly complicated. I started implementing it but it is hard to know if I did it correctly. I was thinking about doing something simpler first and then try the SAT method if we have time. What do you think?

**Comment by warrengm** [comment]
Okay, I implemented two intersects methods for cubes, one that uses absolute bounding boxes, and another that uses SAT.

For collision detection with the big cube, we can check when one of the corners of a smaller cube is no longer inside the big cube. The list of corners (in world coordinates) can  be obtained using the Cube.getVertices() method.

**Comment by warrengm** [comment]
@RobertTatoian I started working on this and its nearly done but it has a bug. What are you working on?

**Comment by bobtat** [comment]
Right now a combination of CSF 524 and our project, I was going to work on applying a scale to the world though pretty soon.

**Comment by bobtat** [comment]
What's the bug with collision detection?
